# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:


buildGoPackage rec {
  name = "vault-le-unstable-${version}";
  version = "2017-12-29";
  rev = "2cf61f92b5d641a7e5c45c20b9da2ce620e25b06";

  goPackagePath = "github.com/arianvp/vault-le";

  src = fetchgit {
    inherit rev;
    url = "git@github.com:arianvp/vault-le.git";
    sha256 = "0j077ys98gb97ffx8kkzi42dx7kih6hsi6xk98g6h87q7zwydw9v";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
