# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/hashicorp/vault";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/vault";
      rev = "f25f546eb9cfb1499076e56cda312451c7fc3f7d";
      sha256 = "1ippnhcz1q5yzwp3a74214i7z7d9arj3af23pw76sp096gck6ci7";
    };
  }
]
